# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_src', models.CharField(max_length=15)),
                ('ip_dst', models.CharField(max_length=15)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('ip_proto', models.CharField(max_length=6)),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('stamp_inserted', models.DateTimeField()),
                ('stamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'acct',
            },
        ),
    ]
