# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=20)),
                ('device_ip', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
