# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20160408_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device1_In',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ip_dst', models.CharField(max_length=15)),
                ('dst_port', models.IntegerField()),
                ('ip_proto', models.CharField(max_length=6)),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('stamp_inserted', models.DateTimeField()),
                ('stamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device1_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device1_Out',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ip_src', models.CharField(max_length=15)),
                ('src_port', models.IntegerField()),
                ('ip_proto', models.CharField(max_length=6)),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('stamp_inserted', models.DateTimeField()),
                ('stamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device1_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device2_In',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ip_dst', models.CharField(max_length=15)),
                ('dst_port', models.IntegerField()),
                ('ip_proto', models.CharField(max_length=6)),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('stamp_inserted', models.DateTimeField()),
                ('stamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device2_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device2_Out',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ip_src', models.CharField(max_length=15)),
                ('src_port', models.IntegerField()),
                ('ip_proto', models.CharField(max_length=6)),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('stamp_inserted', models.DateTimeField()),
                ('stamp_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device2_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billable', models.BooleanField(default=False)),
                ('cost_rate', models.CharField(max_length=10)),
                ('billing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flow.Devices')),
            ],
            options={
                'db_table': 'billing',
            },
        ),
    ]
